mycloud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.views import serve

from pan.urls import router

urlpatterns = [
    path('', include('pan.urls')),
    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('favicon.ico', serve, {'path': 'favicon.ico'}),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + [
        path('__debug__/', include('debug_toolbar.urls'))
    ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = 'pan.views.bad_request_view'
handler403 = 'pan.views.permission_denied_view'
handler404 = 'pan.views.not_found_view'
handler500 = 'pan.views.server_error_view'

pan/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter

from pan import views

app_name = 'pan'

# Главная страница
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('profile', views.ProfileView.as_view(), name='profile'),
    path('cloud', views.CloudView.as_view(), name='cloud'),
    path('history', views.HistoryView.as_view(), name='history'),
    path('bin', views.BinView.as_view(), name='bin'),
    path('detail', views.FileDetailView.as_view(), name='detail'),
]

# поделиться
urlpatterns += [
    path('share-get', views.ShareGetView.as_view(), name='share-get'),
    path('share-create', views.ShareCreateView.as_view(), name='share-create'),
    path('share-update', views.ShareUpdateView.as_view(), name='share-update'),
    path('share-delete', views.ShareDelete.as_view(), name='history-delete'),
    path('share/<str:signature>', views.ShareLinkView.as_view(), name='share-link'),
]

# документ
urlpatterns += [
    path('file-blob/<uuid:uuid>', views.FileBlobView.as_view(), name='file-blob'),
    path('file-delete', views.FileDeleteView.as_view(), name='file-delete'),
    path('file-upload', views.FileUploadView.as_view(), name='file-upload'),
    path('file-trash', views.FileTrashView.as_view(), name='file-trash'),
    path('file-move', views.FileMoveView.as_view(), name='file-move'),
    path('folder-upload', views.FolderUploadView.as_view(), name='folder-upload'),
    path('duplicated-check', views.DuplicatedCheck.as_view(), name='duplicated-check'),
]

# проверять подлинность
urlpatterns += [
    path('login', views.LoginView.as_view(), name='login'),
    path('register', views.RegisterView.as_view(), name='register'),
    path('logout', views.LoginOutView.as_view(), name='logout'),
    path('reset-password', views.ResetPasswordView.as_view(), name='reset-password'),
    path('reset-done/<str:param>', views.ResetDoneView.as_view(), name='reset-done'),
]

# личная информация
urlpatterns += [
    path('alter-avatar', views.AlterAvatarView.as_view(), name='alter-avatar'),
    path('alter-password', views.AlterPasswordView.as_view(), name='alter-password'),
    path('alter-info', views.AlterInfoView.as_view(), name='alter-info'),
    path('msg-appr', views.MsgApprView.as_view(), name='message'),
]

# restful api
router = DefaultRouter(trailing_slash=False)
router.register('cloud', views.CloudViewSet, 'api-cloud')
router.register('history', views.HistoryViewSet, 'api-history')
router.register('bin', views.BinViewSet, 'api-bin')
router.register('folder', views.FolderViewSet, 'api-folder')
router.register('file', views.FileViewSet, 'api-file')
router.register('notice', views.NoticeViewSet, 'api-notice')

pan/forms.py
from django import forms
from django.contrib.auth.validators import UnicodeUsernameValidator


# Форма подтверждения
class UserBaseForm(forms.Form):
    username = forms.CharField(max_length=150, validators=(UnicodeUsernameValidator,))
    password = forms.CharField(min_length=6, max_length=128)
    remember = forms.BooleanField(required=False)


class InfoForm(forms.Form):
    GENDER = [
        ('0', 'Жен'),
        ('1', 'Муж')
    ]

    gender = forms.ChoiceField(choices=GENDER)
    email = forms.EmailField(required=False)


class PasswordForm(forms.Form):
    oldPassword = forms.CharField(min_length=6, max_length=150)
    newPassword = forms.CharField(min_length=6, max_length=150)


class AvatarForm(forms.Form):
    avatar = forms.ImageField()

pan/views.py
from datetime import timedelta
from json import loads as json_loads
from pathlib import Path
from shutil import rmtree, move as file_move
from uuid import UUID

from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.signing import Signer, TimestampSigner, BadSignature, SignatureExpired
from django.core.mail import send_mail
from django.http import FileResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.utils import timezone
from django.views.generic import View, TemplateView, RedirectView
from rest_framework.permissions import IsAuthenticated
from rest_framework.viewsets import ModelViewSet

from .forms import UserBaseForm, InfoForm, AvatarForm, PasswordForm
from .models import (GenericFile, UserFile, UserDir, FileShare, ShareRecord,
                        FileType, UserApproval, UserMessage, Notice)
from .paginations import NoticeResultSetPagination
from .serializers import FileSerializer, FileShareSerializer, FolderSerializer, NoticeSerializer
from .utils import AjaxObj, get_key_signature, get_dir_size, make_archive_bytes, file_size_format


class IndexView(TemplateView):
    """Первая страница"""
    template_name = 'pan/index.html'


class CloudView(LoginRequiredMixin, TemplateView):
    """Облачный диск"""
    template_name = 'pan/cloud.html'


class HistoryView(LoginRequiredMixin, TemplateView):
    """История загрузок"""
    template_name = 'pan/history.html'


class BinView(LoginRequiredMixin, TemplateView):
    """корзина"""
    template_name = 'pan/bin.html'


class FileDetailView(LoginRequiredMixin, TemplateView):
    """Сведения о файле"""
    template_name = 'pan/detail.html'


class ProfileView(LoginRequiredMixin, TemplateView):
    """Личная информация"""
    template_name = 'pan/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        role = self.request.user.profile.role.role_key
        if role == 'common':
            context['applied'] = UserApproval.objects.filter(state='0', create_by=self.request.user).exists()
        context['role'] = role
        context['record'] = UserApproval.objects.filter(create_by=self.request.user)
        context['message'] = UserMessage.objects.filter(create_by=self.request.user)
        return context


class ShareLinkView(TemplateView):
    """Ссылка для получения общих файлов"""
    template_name = 'pan/share.html'

    def get_context_data(self, **kwargs):
        signature = self.kwargs.get('signature')
        context = super().get_context_data()
        try:
            share = FileShare.objects.select_related('user_file').get(secret_key=Signer().unsign(signature))
        except (BadSignature, FileShare.DoesNotExist):
            context['expired'] = True
            return context
        expired = timezone.now() > share.expire_time
        if not expired:
            if self.request.user.is_authenticated:
                ShareRecord.objects.create(file_share=share, recipient=self.request.user)
            else:
                ShareRecord.objects.create(file_share=share, anonymous=self.request.META.get('REMOTE_ADDR'))
            context['file'] = share.user_file
            context['share'] = share
        context['expired'] = expired
        return context


class ResetDoneView(TemplateView):
    """Результат сброса пароля"""
    template_name = 'pan/reset_done.html'

    def get_context_data(self, **kwargs):
        param = self.kwargs.get('param')
        context = super().get_context_data()
        try:
            auth = TimestampSigner().unsign_object(param, max_age=settings.TOKEN_EXPIRY)
            if auth['token'] != settings.RESET_TOKEN:
                context['auth'] = False
            else:
                user = User.objects.get(username=auth['user'])
                user.set_password(settings.RESET_PASSWORD)
                user.save()
                context['auth'] = True
        except (BadSignature, SignatureExpired):
            context['auth'] = False
        return context


class LoginView(View):
    """войти"""

    def post(self, request):
        form = UserBaseForm(request.POST)
        if form.is_valid():
            user = authenticate(request, username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            if user:
                login(request, user)
                if not form.cleaned_data['remember']:
                    request.session.set_expiry(0)
                return AjaxObj(msg='Успешный вход в систему', data=request.session['cloud']).get_response()

            return AjaxObj(400, 'ошибка', {'errors': {'username': ['Неправильное имя пользователя или пароль']}}).get_response()

        return AjaxObj(400, 'ошибка', {'errors': form.errors}).get_response()

class RegisterView(View):
    """регистрация"""
    def post(self, request):
        form = UserBaseForm(request.POST)
        if form.is_valid():
            if User.objects.filter(username=form.cleaned_data['username']).exists():
                return AjaxObj(400, 'ошибка', {'errors': {'username': ['Имя пользователя уже существует']}}).get_response()

            User.objects.create_user(username=form.cleaned_data['username'],
                                     password=form.cleaned_data['password'])
            return AjaxObj(msg='Регистрация прошла успешно').get_response()

        return AjaxObj(400, 'ошибка', {'errors': form.errors}).get_response()


class LoginOutView(RedirectView):
    """опубликовывать"""
    pattern_name = 'pan:index'

    def get(self, request, *args, **kwargs):
        logout(request)
        return super().get(request, *args, **kwargs)


class AlterAvatarView(LoginRequiredMixin, View):
    """Изменить аватар"""

    def post(self, request):
        form = AvatarForm(request.POST, request.FILES)
        if form.is_valid():
            if form.cleaned_data['avatar'].size > settings.MAX_AVATAR_SIZE:
                return AjaxObj(400, f'Загруженное изображение не может быть больше, чем{file_size_format(settings.MAX_AVATAR_SIZE)}').get_response()
            profile = request.user.profile
            profile.avatar = form.cleaned_data['avatar']
            profile.update_by = request.user
            profile.save()
            return AjaxObj(msg='Загрузка прошла успешно').get_response()

        return AjaxObj(400, 'Незаконные файлы').get_response()


class AlterPasswordView(LoginRequiredMixin, View):
    """Поменять пароль"""

    def post(self, request):
        form = PasswordForm(request.POST)
        if form.is_valid():
            if request.user.check_password(form.cleaned_data['oldPassword']):
                request.user.set_password(form.cleaned_data['newPassword'])
                request.user.save()
                return AjaxObj(msg='Успешно модифицировано').get_response()

            return AjaxObj(400, 'ошибка', {'errors': {'oldPassword': ['Исходный пароль неверен']}}).get_response()

        return AjaxObj(400, 'ошибка', {'errors': form.errors}).get_response()


class ResetPasswordView(View):
    """Сброс пароля"""

    def post(self, request):
        username = request.POST.get('resetName').strip()
        queryset = User.objects.filter(username=username)
        if not queryset.exists():
            return AjaxObj(400, 'ошибка', {'errors': {'resetName': ['Имя пользователя не существует']}}).get_response()

        user = queryset.get()
        if user.email == '':
            return AjaxObj(400, 'ошибка', {'errors': {'resetName': ['Пользователь не привязан к почтовому ящику']}})\
                .get_response()

        auth = {'user': user.username, 'token': settings.RESET_TOKEN}
        context = {'scheme': request.META.get('wsgi.url_scheme'),
                   'host': request.META.get('HTTP_HOST'),
                   'param': TimestampSigner().sign_object(auth),
                   'password': settings.RESET_PASSWORD}
        html = render_to_string('pan/reset.html', context)
        send_mail(
            subject='Tiny Cloud',
            message=html,
            from_email=None,
            recipient_list=[user.email],
            fail_silently=True,
            html_message=html
        )
        return AjaxObj(msg='Электронное письмо с подтверждением было отправлено').get_response()


class AlterInfoView(LoginRequiredMixin, View):
    """Изменять информацию"""

    def post(self, request):
        form = InfoForm(request.POST)
        if form.is_valid():
            user = request.user
            profile = user.profile
            email = form.cleaned_data['email']
            gender = form.cleaned_data['gender']
            if email != '' and User.objects.filter(email=email).exclude(username=user.username).exists():
                return AjaxObj(400, 'ошибка', {'errors': {'email': ['Пользователь уже привязал почтовый ящик']}})\
                    .get_response()

            profile.gender = gender
            profile.update_by = user
            user.email = email
            profile.save()
            user.save()
            return AjaxObj(msg='Изменение было успешным').get_response()

        return AjaxObj(400, 'ошибка', {'errors': form.errors}).get_response()


class MsgApprView(LoginRequiredMixin, View):
    """Приложение и сообщение"""

    def post(self, request):
        message = request.POST.get('message').strip()
        if message == '' or message is None:
            return AjaxObj(400, 'Незаконная информация').get_response()
        if request.POST.get('way') == 'apply':
            msg = 'Успешно поданная заявка'
            UserApproval.objects.create(content=message, create_by=request.user)
        else:
            msg = 'Спасибо вам за ваше сообщение'
            UserMessage.objects.create(content=message, create_by=request.user)
        return AjaxObj(200, msg).get_response()

pan/templates/pan/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.bootcdn.net/ajax/libs/mdb-ui-kit/3.9.0/mdb.min.css" rel="stylesheet">
    <link href="https://cdn.bootcdn.net/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
    <link href="{% static 'pan/css/common.css' %}" rel="stylesheet">
    {% block styles %}{% endblock %}{# css стиль #}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<header>
    {# Боковая панель #}
    <div class="offcanvas offcanvas-start bg-white border-end-0 shadow-2" data-mdb-scroll="true"
         data-mdb-backdrop="false" tabindex="-1" id="sidebar" style="width: 240px; height: 100vh; z-index: 1035">
        <div class="offcanvas-header">
            <h5 class="offcanvas-title">
                <a class="icon-link" href="{% url 'pan:index' %}" style="padding: 0.625rem 1.5rem 0.5rem;">
                    <i class="fab fa-cloudscale fa-3x"></i>
                </a>
            </h5>
            <a class="icon-link d-block d-lg-none" data-mdb-dismiss="offcanvas"
               style="padding: 0.625rem 1.5rem 0.5rem;">
                <i class="fas fa-times fa-2x"></i>
            </a>
        </div>
        <div class="offcanvas-body d-flex flex-column mt-5">
            <div class="flex-shrink-0 nav nav-tabs flex-column align-items-right" id="v-tabs-tab">
                {% block sidenavs %}
                    <a class="nav-link fs-6" id="cloudTab" href="{% url 'pan:cloud' %}">
                        <i class="fas fa-cloud me-2"></i>Мой облачный диск
                    </a>
                    <a class="nav-link fs-6" id="historyTab" href="{% url 'pan:history' %}">
                        <i class="fas fa-history me-2"></i>История загрузок
                    </a>
                    <a class="nav-link fs-6" id="binTab" href="{% url 'pan:bin' %}">
                        <i class="fas fa-trash me-2"></i>Корзина
                    </a>
                {% endblock %}
            </div>
            <div class="mt-auto">
                <div class="card" id="memory">
                    <div class="card-body">
                        <div class="card-text">
                            <i class="fas fa-cog me-2"></i>
                            <small class="text-muted">
                                Размер диска：<br>
                                <sapn id="storage"></sapn>
                                / <span id="used"></span>
                            </small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {# Боковая панель #}
    {# Панель навигации #}
    <nav class="navbar sidenav navbar-expand-lg navbar-light bg-white fixed-top shadow-2">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" id="sidebarBtn" data-mdb-toggle="offcanvas"
                    data-mdb-target="#sidebar">
                <i class="fas fa-bars"></i>
            </button>
            <div class="d-none d-sm-flex input-group w-auto">
                <input type="search" class="form-control rounded search" placeholder="поиск" autocomplete="off"/>
                <span class="input-group-text border-0">
                    <i class="fas fa-search"></i>
                </span>
            </div>
            <div class="navbar-nav flex-row ms-auto align-items-center">
                <a class="nav-link px-2 dropdown-toggle hidden-arrow" data-mdb-toggle="dropdown" id="notice">
                    <i class="fas fa-bell"></i>
                </a>
                <ul class="dropdown-menu dropdown-menu-end"
                    style="width: 300px; max-height: 350px; overflow-y: auto"></ul>
                <a class="nav-link px-2" data-mdb-toggle="tooltip" data-mdb-placement="bottom" title="обновления">
                    <i class="fas fa-question-circle"></i>
                </a>
                <a class="nav-link px-2" href="{% url 'pan:profile' %}" data-mdb-toggle="tooltip"
                   data-mdb-placement="bottom" title="настройки профиля">
                    <img src="{{ user.profile.avatar.url }}" class="rounded-circle" height="25" width="25"
                         alt="avatar"/>
                </a>
            </div>
        </div>
    </nav>
    {# Панель навигации #}
</header>
<main class="main-container">
    <div class="container-lg px-lg-4">
        {% block search %}
            <div class="input-group d-flex d-sm-none">
                <input type="search" class="form-control rounded search" placeholder="поиск" autocomplete="off"/>
                <span class="input-group-text border-0">
                <i class="fas fa-search"></i>
            </span>
            </div>
        {% endblock %}
        {% block content %}{% endblock %}
    </div>
</main>
{# Окно подтверждения #}
<div class="modal fade" id="modal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body text-center">
                <h5 class="mb-4 modal-title"></h5>
                <div class="modal-btn">
                    <button class="btn btn-light" data-mdb-dismiss="modal">отменить</button>
                    <button class="btn btn-danger">подтвердить</button>
                </div>
            </div>
        </div>
    </div>
</div>
{# Окно подтверждения #}
{# alert #}
<div class="alert alert-info translate-middle px-2 py-1 fade hide" id="alert"
     style="z-index: 1; position: absolute; left: 50%; top: -20%">
    <i class="fas fa-check-circle"></i><span class="ps-2 alert-content">Копирование успешно</span>
</div>
{# alert #}
{# Уведомление о проверке #}
<div class="position-fixed bottom-0 end-0 p-3" style="z-index: 5">
    <div id="toast" class="toast fade hide">
        <div class="toast-header">
            <i></i>
            <button type="button" class="ms-auto btn-close" data-mdb-dismiss="toast"></button>
        </div>
        <div class="toast-body"></div>
    </div>
</div>
{# Уведомление о проверке #}
{% block componets %}{% endblock %} {# компонент #}
<script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdn.bootcdn.net/ajax/libs/mdb-ui-kit/3.9.0/mdb.min.js"></script>
<script src="{% static 'pan/js/utils.js' %}"></script>
<script src="{% static 'pan/js/config.js' %}"></script>
<script src="{% static 'pan/js/responsive.js' %}"></script>
{% block scripts %}{% endblock %}{# js документ #}
</body>
</html>

pan/templates/pan/bin.html
{% extends 'pan/base.html' %}
{% load static %}

{% block styles %}
    <link href="https://cdn.staticfile.org/bootstrap-table/1.19.1/bootstrap-table.min.css" rel="stylesheet">
{% endblock %}

{% block title %}корзина{% endblock %}

{% block sidenavs %}
    <a class="nav-link fs-6" id="cloudTab" href="{% url 'pan:cloud' %}">
        <i class="fas fa-cloud me-2"></i>МОЙ ОБЛАЧНЫЙ ДИСК
    </a>
    <a class="nav-link fs-6" id="historyTab" href="{% url 'pan:history' %}">
        <i class="fas fa-history me-2"></i>ИСТОРИЯ ЗАГРУЗОК
    </a>
    <a class="nav-link fs-6 active" id="binTab" href="{% url 'pan:bin' %}">
        <i class="fas fa-trash me-2"></i>КОРЗИНА
    </a>
{% endblock %}

{% block content %}
    <div id="toolbar">
        <div class="float-end btn-group shadow-0" role="group">
            <button type="button" id="recycleBtn" class="btn btn-light" data-mdb-toggle="tooltip"
                    data-mdb-placement="bottom" title="восстановление"><i class="fas fa-undo-alt"></i></button>
            <button type="button" id="delBtn" class="btn btn-light" data-mdb-toggle="tooltip"
                    data-mdb-placement="bottom" title="стереть"><i class="fas fa-trash"></i></button>
            <button type="button" id="sortBy" class="btn btn-light dropdown-toggle hidden-arrow "
                    data-mdb-toggle="dropdown" data-mdb-placement="bottom" data-custom-sort="create_time">Время загрузки
            </button>
            <button type="button" id="sortOrder" class="btn btn-light px-2"
                    data-mdb-placement="bottom"
                    data-custom-order="desc"><i class="fas fa-sort-down"></i>
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item sort" data-custom-sort="file_name"
                       href="javascript:void (0)">Имя файла</a></li>
                <li><a class="dropdown-item sort" data-custom-sort="file_size"
                       href="javascript:void (0)">Размер файла</a></li>
                <li><a class="dropdown-item sort" data-custom-sort="create_time"
                       href="javascript:void (0)">Время загрузки</a></li>
            </ul>
        </div>
        <div class="pb-3 card" style="clear: both"></div>
    </div>
    <table id="binTable"></table>
{% endblock %}

{% block scripts %}
    <script src="https://cdn.staticfile.org/bootstrap-table/1.19.1/bootstrap-table.min.js"></script>
    <script src="https://cdn.staticfile.org/bootstrap-table/1.19.1/locale/bootstrap-table-zh-CN.min.js"></script>
    <script src="//at.alicdn.com/t/font_2926309_gvlwiirwihf.js"></script>
    <script src="{% static 'pan/js/common-table.js' %}"></script>
    <script src="{% static 'pan/js/bin-table.js' %}"></script>
{% endblock %}

pan/templates/pan/history.html
{% extends 'pan/base.html' %}
{% load static %}

{% block styles %}
    <link href="https://cdn.staticfile.org/bootstrap-table/1.19.1/bootstrap-table.min.css" rel="stylesheet">
{% endblock %}

{% block title %}История загрузок{% endblock %}

{% block sidenavs %}
    <a class="nav-link fs-6" id="cloudTab" href="{% url 'pan:cloud' %}">
        <i class="fas fa-cloud me-2"></i>Мой облачный диск
    </a>
    <a class="nav-link fs-6 active" id="historyTab" href="{% url 'pan:history' %}">
        <i class="fas fa-history me-2"></i>История загрузок
    </a>
    <a class="nav-link fs-6" id="binTab" href="{% url 'pan:bin' %}">
        <i class="fas fa-trash me-2"></i>Корзина
    </a>
{% endblock %}

{% block content %}
    <div id="toolbar">
        <div class="float-end btn-group shadow-0" role="group">
            <button type="button" id="delBtn" class="btn btn-light" data-mdb-toggle="tooltip"
                    data-mdb-placement="bottom" title="удалить"><i class="fas fa-trash"></i></button>
            <button type="button" id="sortBy" class="btn btn-light dropdown-toggle hidden-arrow "
                    data-mdb-toggle="dropdown" data-mdb-placement="bottom" data-custom-sort="create_time">Время создания
            </button>
            <button type="button" id="sortOrder" class="btn btn-light px-2"
                    data-mdb-placement="bottom"
                    data-custom-order="desc"><i class="fas fa-sort-down"></i>
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item sort" data-custom-sort="expire_time"
                       href="javascript:void (0)">Срок годности</a></li>
                <li><a class="dropdown-item sort" data-custom-sort="create_time"
                       href="javascript:void (0)">Время создания</a></li>
            </ul>
        </div>
        <div class="pb-3 card" style="clear: both"></div>
    </div>
    <table id="historyTable"></table>
{% endblock %}

{% block componets %}{# Настройки ссылок #}
    <div class="modal fade" id="shareModal" data-custom-id="">
        <div class="modal-dialog modal-lg modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header border-bottom-0">
                    <h5 class="modal-title">Настройки ссылок</h5>
                    <button type="button" class="btn-close" data-mdb-dismiss="modal"></button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-6 border-end">
                            <div class="mb-3">
                                <p>Обмен ссылками</p>
                                <div class="bg-image hover-overlay ripple copy-text text-center w-100">
                                    <div class="border rounded text-truncate py-2 px-1" id="shareLink"></div>
                                    <a href="javascript:void(0)" class="text-dark copy-mask">
                                        <div class="mask rounded p-2" style="background-color: #EEEEEE">копировать</div>
                                    </a>
                                </div>
                            </div>
                            <div class="mb-3">
                                <p>Общий доступ к паролю</p>
                                <div class="bg-image hover-overlay ripple copy-text text-center">
                                    <div class="w-100 border rounded py-2 px-1" id="shareKey"></div>
                                    <a href="javascript:void(0)" class="text-dark copy-mask">
                                        <div class="mask rounded p-2" style="background-color: #EEEEEE">копировать</div>
                                    </a>
                                </div>
                            </div>
                            <div class="mb-3 text-center">
                                <button class="btn btn-info">Копирование одним щелчком мыши</button>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <p>установить</p>
                            <div class="d-flex align-items-center mb-3">
                                <div>срок годности</div>
                                <div class="dropdown ms-auto">
                                    <sapn class="me-1" id="delta" data-custom-delta="">Пожалуйста выберите</sapn>
                                    <a class="icon-link hidden-arrow" href="javascript:void (0)"
                                       data-mdb-toggle="dropdown">
                                        <i class="fas fa-angle-down"></i>
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <li><a class="dropdown-item" data-custom-delta="1"
                                               href="javascript:void (0)">1 день</a></li>
                                        <li><a class="dropdown-item" data-custom-delta="7"
                                               href="javascript:void (0)">7 дней</a></li>
                                        <li><a class="dropdown-item" data-custom-delta="30" href="javascript:void (0)">30 дней</a>
                                        </li>
                                        <li><a class="dropdown-item" data-custom-delta="999" href="javascript:void (0)">бессрочный</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="mb-3">
                                <p>Дополнительное описание</p>
                                <div class="form-outline">
                                    <textarea class="form-control border" id="summary" rows="3"
                                              maxlength="100"></textarea>
                                    <label class="form-label copy-text">Эта информация будет отображена общему пользователю</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}{# Настройки ссылок #}

{% block scripts %}
    <script src="https://cdn.staticfile.org/bootstrap-table/1.19.1/bootstrap-table.min.js"></script>
    <script src="https://cdn.staticfile.org/bootstrap-table/1.19.1/locale/bootstrap-table-zh-CN.min.js"></script>
    <script src="//at.alicdn.com/t/font_2926309_gvlwiirwihf.js"></script>
    <script src="{% static 'pan/js/common-table.js' %}"></script>
    <script src="{% static 'pan/js/history-table.js' %}"></script>
{% endblock %}

pan/templates/pan/reset.html
<div>
    <h3>сброс My Cloud пароля учетной записи</h3>
    <a class="btn" href="{{ scheme }}://{{ host }}{% url 'pan:reset-done' param %}" target="_blank">Сброс пароля</a>
    <p>Привет, пользователь. Получен ваш запрос на сброс пароля. Пожалуйста, подтвердите, действительно ли это вы запрашивали</p>
    <p>Нажмите кнопку выше в течение 30 минут, чтобы сбросить пароль вашей учетной записи на{{ password }}. Пожалуйста, измените свой пароль как можно скорее после сброса。</p>
    <p>Спасибо！<br>
        My Cloud
    </p>
</div>